# Generated by Django 2.0 on 2018-02-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=100)),
                ('stored', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Data',
                'verbose_name_plural': 'Email Data',
            },
        ),
    ]
