# Generated by Django 2.0 on 2018-02-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_data',
            name='email_id',
        ),
        migrations.AddField(
            model_name='email_data',
            name='EMAIL_ID',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
