# Generated by Django 2.0 on 2018-02-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180215_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_data',
            name='EMAIL_ID',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
